### ISSUE TITLE
Can't drag items into actions tab

### ISSUE THREAD

**Issue by stygiansabyss** [Farratto/JackOfAllThings#1]
Without this extension, a user can drag items from the items window to their action tab and it will create an entry and do its best to find actions based on the words in the item description.

![image](https://github.com/user-attachments/assets/fe2add8c-9119-45ef-a987-4fa8f29a4ab3)

With the Jack of All Things extension installed, this does not work.  My main concern here is that in the case of health potions, FGU does a good job of figuring all of this out on its own.  More importantly, it allows players to use the preparation mode to set how many they have.  This is not doable any longer with this extension in effect.

Is there a way to not have this extension override that base functionality?

Thank

**Comment by Farratto** [comment]
I'm sorry.  I don't know what you mean.  What ruleset are you using?  I tried dragging items into a character's action tab with no extensions loaded and nothing happens.
